[theme]
primaryColor = "#FF4B4B"  # Change this to your desired primary color
backgroundColor = "#FFFFFF"  # Background color of the app
secondaryBackgroundColor = "#F0F0F0"  # Sidebar background color
textColor = "#000000"  # Text color
font = "sans serif"  # Font style (options: "sans serif", "serif", "monospace")
